import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const downloadPDF = (cgpa: number, totalSubjects: number, grades: Record<string, number>) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(0, 0, 0);
  doc.text('SIMATS ENGINEERING', 105, 20, { align: 'center' });
  
  doc.setFontSize(16);
  doc.text('CGPA CALCULATION REPORT', 105, 30, { align: 'center' });
  
  // Line
  doc.setLineWidth(0.5);
  doc.line(20, 35, 190, 35);
  
  // CGPA Result
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('CGPA RESULT', 20, 50);
  
  doc.setFontSize(24);
  doc.setTextColor(0, 100, 200);
  doc.text(`${cgpa.toFixed(2)}`, 20, 65);
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Total Subjects: ${totalSubjects}`, 20, 75);
  
  // Grade breakdown
  doc.setFontSize(14);
  doc.text('GRADE BREAKDOWN', 20, 95);
  
  let yPos = 105;
  Object.entries(grades).forEach(([grade, count]) => {
    if (count > 0) {
      doc.setFontSize(12);
      doc.text(`Grade ${grade}: ${count} subjects`, 20, yPos);
      yPos += 10;
    }
  });
  
  // Footer
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by SIMATS CGPA Calculator', 20, 280);
  doc.text(`© ${new Date().getFullYear()} Designed by Donavalli Jayanth`, 20, 290);
  
  doc.save('SIMATS_CGPA_Result.pdf');
};

export const downloadImage = async (elementId: string) => {
  const element = document.getElementById(elementId);
  if (!element) return;
  
  const canvas = await html2canvas(element, {
    backgroundColor: '#0f172a',
    scale: 2,
    useCORS: true
  });
  
  const link = document.createElement('a');
  link.download = 'SIMATS_CGPA_Result.png';
  link.href = canvas.toDataURL();
  link.click();
};