import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

const loadImageAsBase64 = (url: string): Promise<string> => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      if (!ctx) { reject('No context'); return; }
      ctx.drawImage(img, 0, 0);
      resolve(canvas.toDataURL('image/png'));
    };
    img.onerror = reject;
    img.src = url;
  });
};

export const downloadPDF = async (cgpa: number, totalSubjects: number, grades: Record<string, number>) => {
  const doc = new jsPDF();

  // Load and add SIMATS logo
  try {
    const logoData = await loadImageAsBase64('/logo2.png');
    doc.addImage(logoData, 'PNG', 85, 6, 30, 30);
  } catch {
    // Fallback if logo fails to load
  }

  // Header
  doc.setFontSize(20);
  doc.setTextColor(23, 59, 108);
  doc.text('SIMATS ENGINEERING', 105, 42, { align: 'center' });

  doc.setFontSize(14);
  doc.setTextColor(20, 157, 221);
  doc.text('CGPA CALCULATION REPORT', 105, 50, { align: 'center' });

  // Line
  doc.setLineWidth(0.5);
  doc.setDrawColor(20, 157, 221);
  doc.line(20, 55, 190, 55);

  // CGPA Result
  doc.setFontSize(14);
  doc.setTextColor(23, 59, 108);
  doc.text('CGPA RESULT', 20, 70);

  doc.setFontSize(36);
  doc.setTextColor(20, 157, 221);
  doc.text(`${cgpa.toFixed(2)}`, 20, 88);

  doc.setFontSize(12);
  doc.setTextColor(80, 80, 80);
  doc.text(`Total Subjects: ${totalSubjects}`, 20, 98);

  // Grade breakdown
  doc.setFontSize(14);
  doc.setTextColor(23, 59, 108);
  doc.text('GRADE BREAKDOWN', 20, 118);

  let yPos = 130;
  Object.entries(grades).forEach(([grade, count]) => {
    if (count > 0) {
      doc.setFontSize(12);
      doc.setTextColor(60, 60, 60);
      doc.text(`Grade ${grade}: ${count} subjects`, 20, yPos);
      yPos += 10;
    }
  });

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text('Generated by SIMATS CGPA Calculator — simatscgpa.netlify.app', 105, 280, { align: 'center' });
  doc.text(`© ${new Date().getFullYear()} Designed by Donavalli Jayanth`, 105, 290, { align: 'center' });

  doc.save('SIMATS_CGPA_Result.pdf');
};

export const downloadImage = async (elementId: string) => {
  const element = document.getElementById(elementId);
  if (!element) return;

  const canvas = await html2canvas(element, {
    backgroundColor: '#0f172a',
    scale: 2,
    useCORS: true
  });

  const link = document.createElement('a');
  link.download = 'SIMATS_CGPA_Result.png';
  link.href = canvas.toDataURL();
  link.click();
};

interface ShareData {
  title: string;
  text: string;
}

export const shareResultImage = async (elementId: string, shareData: ShareData) => {
  const element = document.getElementById(elementId);
  if (!element) return;

  try {
    // Generate high-quality branded canvas
    const canvas = await html2canvas(element, {
      backgroundColor: '#0f172a',
      scale: 3,
      useCORS: true,
      logging: false,
    });

    // Add watermark/branding overlay
    const ctx = canvas.getContext('2d');
    if (ctx) {
      const scale = 3; // Matches your html2canvas scale
      
      // 1. Scale the bar height appropriately so it looks right on high-res exports
      const barHeight = 80 * scale; 
      
      // 2. Create a strict vertical gradient (x1, y1, x2, y2)
      const gradient = ctx.createLinearGradient(0, canvas.height - barHeight, 0, canvas.height);
      
      // 3. Start completely transparent (opacity 0) to avoid the "harsh line"
      gradient.addColorStop(0, 'rgba(15, 23, 42, 0)');
      // Fade into a solid dark color at the bottom to make the text pop
      gradient.addColorStop(1, 'rgba(15, 23, 42, 0.95)');
      
      ctx.fillStyle = gradient;
      ctx.fillRect(0, canvas.height - barHeight, canvas.width, barHeight);

      // 4. Scale the text and positioning so it doesn't look microscopic on mobile
      ctx.fillStyle = 'rgba(255, 255, 255, 0.9)';
      ctx.font = `bold ${16 * scale}px Inter, sans-serif`;
      ctx.textAlign = 'right';
      ctx.fillText('SIMATS CGPA Calculator', canvas.width - (24 * scale), canvas.height - (36 * scale));

      ctx.fillStyle = 'rgba(148, 163, 184, 0.8)';
      ctx.font = `${12 * scale}px Inter, sans-serif`;
      ctx.fillText('simatscgpa.netlify.app', canvas.width - (24 * scale), canvas.height - (16 * scale));
    }

    const blob = await new Promise<Blob | null>((resolve) => {
      canvas.toBlob((b) => resolve(b), 'image/png');
    });

    if (!blob) return;

    const file = new File([blob], 'SIMATS_CGPA_Result.png', { type: 'image/png' });

    // Try native Web Share API first
    if (navigator.share && navigator.canShare?.({ files: [file] })) {
      await navigator.share({
        ...shareData,
        files: [file],
      });
    } else if (navigator.share) {
      // Share without files
      await navigator.share(shareData);
    } else {
      // Fallback: download the image
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = 'SIMATS_CGPA_Result.png';
      link.click();
      URL.revokeObjectURL(url);
    }
  } catch (err) {
    // User cancelled or error — silent fail
    console.log('Share cancelled or failed', err);
  }
};